### ISSUE TITLE
investigate re-exporting individual protobuf message types from `@penumbra-zone/protobuf`

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1503] opened 2024-07-17 23:09 UTC
here's the current frequency of each individual message type import

data collected with

`rg --multiline "import \{([\n\s\w,]+)\} from ('@buf/.+');" --replace '$2$1'` and then a bunch of iterative manipulation, sorry

```
  83 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/asset/v1/asset_pb.js' Metadata
  51 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/asset/v1/asset_pb.js' ValueView
  40 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' BalancesResponse
  30 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/asset/v1/asset_pb.js' AssetId
  26 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/keys/v1/keys_pb.js' Address
  22 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/num/v1/num_pb.js' Amount
  21 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/keys/v1/keys_pb.js' FullViewingKey
  20 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/auction/v1/auction_pb.js' AuctionId
  17 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' SpendableNoteRecord
  17 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' ValidatorInfo
  16 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/keys/v1/keys_pb.js' AddressView
  15 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' TransactionPlannerRequest
  15 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' SwapRecord
  15 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/keys/v1/keys_pb.js' AddressIndex
  15 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/auction/v1/auction_pb.js' DutchAuction
  14 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/transaction/v1/transaction_pb.js' Transaction
  12 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' TransactionInfo
  12 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/txhash/v1/txhash_pb.js' TransactionId
  12 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/transaction/v1/transaction_pb.js' TransactionPlan
  12 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/auction/v1/auction_pb.js' DutchAuctionDescription
  12 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/asset/v1/asset_pb.js' Value
   8 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/crypto/tct/v1/tct_pb.js' StateCommitment
   8 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/transaction/v1/transaction_pb.js' TransactionView
   8 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/keys/v1/keys_pb.js' IdentityKey
   8 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' ValidatorInfoResponse
   8 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/app/v1/app_pb.js' AppParameters
   7 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' SwapView
   7 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' PositionId
   6 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' BalancesRequest
   6 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/keys/v1/keys_pb.js' WalletId
   6 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/keys/v1/keys_pb.js' SpendKey
   6 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/shielded_pool/v1/shielded_pool_pb.js' SpendView
   6 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/shielded_pool/v1/shielded_pool_pb.js' OutputView
   6 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/fee/v1/fee_pb.js' GasPrices
   5 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/transaction/v1/transaction_pb.js' AuthorizationData
   5 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/transaction/v1/transaction_pb.js' ActionView
   5 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' ValidatorState_ValidatorStateEnum
   5 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/shielded_pool/v1/shielded_pool_pb.js' FmdParameters
   5 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/sct/v1/sct_pb.js' Epoch
   5 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' SwapExecution_Trace
   5 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' PositionState
   5 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/asset/v1/asset_pb.js' EstimatedPrice
   4 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' UnbondingTokensByAddressIndexResponse
   4 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' DelegationsByAddressIndexResponse
   4 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' BroadcastTransactionResponse
   4 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' AuthorizeAndBuildResponse
   4 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' AssetMetadataByIdRequest
   4 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/crypto/tct/v1/tct_pb.js' MerkleRoot
   4 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/transaction/v1/transaction_pb.js' WitnessData
   4 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/sct/v1/sct_pb.js' Nullifier
   4 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/fee/v1/fee_pb.js' Fee
   4 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' TradingPair
   4 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' SwapClaimView
   4 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' Position
   4 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' BatchSwapOutputData
   4 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/compact_block/v1/compact_block_pb.js' CompactBlock
   3 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' WitnessAndBuildResponse
   3 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' TransactionPlannerRequest_Swap
   3 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' StatusResponse
   3 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' NotesForVotingResponse
   3 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' AppParametersResponse
   3 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/custody/v1/custody_pb.js' AuthorizeRequest
   3 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/transaction/v1/transaction_pb.js' MemoView
   3 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/transaction/v1/transaction_pb.js' ActionPlan
   3 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/transaction/v1/transaction_pb.js' Action
   3 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' ValidatorPenaltyResponse
   3 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' ValidatorPenaltyRequest
   3 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' ValidatorInfoRequest
   3 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/shielded_pool/v1/shielded_pool_pb.js' NoteView
   3 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' CandlestickData
   3 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/auction/v1/auction_pb.js' ActionDutchAuctionEnd
   3 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/asset/v1/asset_pb.js' EquivalentValue
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' UnclaimedSwapsResponse
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' UnbondingTokensByAddressIndexRequest_Filter
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' TransactionPlannerRequest_Output
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' TransactionPlannerRequest_ActionDutchAuctionSchedule
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' TransactionInfoResponse
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' StatusRequest
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' DelegationsByAddressIndexRequest_Filter
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' BroadcastTransactionRequest
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' AuctionsResponse
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' AssetsResponse
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' AssetMetadataByIdResponse
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' AppParametersRequest
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' AddressByIndexResponse
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' AddressByIndexRequest
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/transaction/v1/transaction_pb.js' TransactionPerspective
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/transaction/v1/transaction_pb.js' MemoView_Visible
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/keys/v1/keys_pb.js' AddressView_Decoded
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' Validator
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' UndelegateClaimBody
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' UndelegateClaim
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' Undelegate
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' GetValidatorInfoResponse
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' Delegate
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/shielded_pool/v1/shielded_pool_pb.js' Note
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/fee/v1/fee_pb.js' FeeTier_Tier
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' SwapPlaintext
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' Swap
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' PositionState_PositionStateEnum
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/auction/v1/auction_pb.js' ActionDutchAuctionWithdrawView
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/auction/v1/auction_pb.js' ActionDutchAuctionWithdrawPlan
   2 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/asset/v1/asset_pb' Metadata
   2 '@buf/cosmos_ibc.bufbuild_es/ibc/lightclients/tendermint/v1/tendermint_pb.js' ClientState
   2 '@buf/cosmos_ibc.bufbuild_es/ibc/core/client/v1/query_pb.js' QueryClientStatesResponse
   2 '@buf/cosmos_ibc.bufbuild_es/ibc/core/client/v1/query_pb.js' QueryClientStatesRequest
   2 '@buf/connectrpc_eliza.connectrpc_es/connectrpc/eliza/v1/eliza_connect.js' ElizaService
   2 '@buf/connectrpc_eliza.bufbuild_es/connectrpc/eliza/v1/eliza_pb.js' SayRequest
   1 '@buf/tendermint_tendermint.bufbuild_es/tendermint/crypto/keys_pb.js' PublicKey
   1 '@buf/penumbra-zone_penumbra.connectrpc_query-es/penumbra/view/v1/view-ViewService_connectquery' addressByIndex
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' WitnessResponse
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' WitnessRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' WitnessAndBuildRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' UnclaimedSwapsRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' UnbondingTokensByAddressIndexRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' TransactionPlannerResponse
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' TransactionPlannerRequest_UndelegateClaim
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' TransactionPlannerRequest_Spend
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' TransactionPlannerRequest_ActionDutchAuctionWithdraw
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' TransactionPlannerRequest_ActionDutchAuctionEnd
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' TransactionInfoRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' TransactionInfoByHashResponse
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' TransactionInfoByHashRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' SwapByCommitmentResponse
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' SwapByCommitmentRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' StatusStreamResponse
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' StatusStreamRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' OwnedPositionIdsResponse
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' OwnedPositionIdsRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' NullifierStatusRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' NotesResponse
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' NotesRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' NotesForVotingRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' NoteByCommitmentResponse
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' NoteByCommitmentRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' IndexByAddressRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' GasPricesResponse
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' GasPricesRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' FMDParametersResponse
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' FMDParametersRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' EphemeralAddressResponse
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' EphemeralAddressRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' DelegationsByAddressIndexRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' AuthorizeAndBuildRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' AuctionsRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb.js' AssetsRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/view/v1/view_pb' BalancesResponse
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/util/tendermint_proxy/v1/tendermint_proxy_pb.js' SyncInfo
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/util/tendermint_proxy/v1/tendermint_proxy_pb.js' GetStatusResponse
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/transaction/v1/transaction_pb.js' MemoPlaintext
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/keys/v1/keys_pb.js' GovernanceKey
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/keys/v1/keys_pb' AddressIndex
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' ValidatorStatus
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' ValidatorState
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' RateData
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' GetValidatorInfoRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' FundingStream
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' BondingState_BondingStateEnum
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/stake/v1/stake_pb.js' BondingState
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/shielded_pool/v1/shielded_pool_pb.js' SpendView_Visible
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/shielded_pool/v1/shielded_pool_pb.js' SpendPlan
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/shielded_pool/v1/shielded_pool_pb.js' OutputView_Visible
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/shielded_pool/v1/shielded_pool_pb.js' OutputPlan
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/sct/v1/sct_pb.js' SctParameters
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/sct/v1/sct_pb.js' EpochByHeightResponse
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/sct/v1/sct_pb.js' EpochByHeightRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/sct/v1/sct_pb.js' CommitmentSource
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/ibc/v1/ibc_pb.js' Ics20Withdrawal
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' SwapView_Opaque
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' SwapPlan
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' SwapExecution
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' SwapClaimView_Opaque
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' SwapClaimPlan
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' SwapBody
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' SimulateTradeResponse
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/dex/v1/dex_pb.js' SimulateTradeRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/compact_block/v1/compact_block_pb.js' CompactBlockRangeRequest
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/auction/v1/auction_pb.js' DutchAuctionState
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/auction/v1/auction_pb.js' ActionDutchAuctionScheduleView
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/component/auction/v1/auction_pb.js' ActionDutchAuctionSchedule
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/asset/v1/asset_pb.js' ValueView_KnownAssetId
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/asset/v1/asset_pb.js' Denom
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/asset/v1/asset_pb' ValueView
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/core/asset/v1/asset_pb' AssetId
   1 '@buf/penumbra-zone_penumbra.bufbuild_es/penumbra/cnidarium/v1/cnidarium_pb.js' KeyValueRequest
   1 '@buf/cosmos_ibc.bufbuild_es/ibc/lightclients/tendermint/v1/tendermint_pb.js' Header
   1 '@buf/cosmos_ibc.bufbuild_es/ibc/core/client/v1/tx_pb.js' MsgUpdateClient
   1 '@buf/cosmos_ibc.bufbuild_es/ibc/core/client/v1/client_pb.js' Height
   1 '@buf/cosmos_ibc.bufbuild_es/ibc/core/channel/v1/tx_pb.js' MsgRecvPacket
   1 '@buf/cosmos_ibc.bufbuild_es/ibc/core/channel/v1/channel_pb.js' Channel
   1 '@buf/connectrpc_eliza.bufbuild_es/connectrpc/eliza/v1/eliza_pb.js' SayResponse
   1 '@buf/connectrpc_eliza.bufbuild_es/connectrpc/eliza/v1/eliza_pb.js' IntroduceRequest
```

**Comment by VanishMax** [comment] 2024-07-18 08:06
Duplicate of #1483. Still nice to see the list of all protobuf messages

**Closed** 2024-08-24 09:37 UTC
