### ISSUE TITLE
filter zero-valued notes from spendable note set 

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1415] opened 2024-07-04 03:13 UTC
zero-valued notes should not be in spendable note record (SNR) set, since it may cause a transaction to fail. see https://github.com/penumbra-zone/penumbra/issues/2135 and https://github.com/penumbra-zone/penumbra/issues/2142

currently, we filter them out in the wasm [planner](https://github.com/penumbra-zone/web/pull/1333/files#diff-ec51d55a0b0ab2ce263357c3d43509ddfe1d88ace8bc963213a0899cca79a0f0R509), but it's probably better to just not include them in the SNR in the first place.

-----------------------------------------------------------------------------------------------------------------------------------

https://github.com/penumbra-zone/web/assets/70081547/2ab01352-33f7-41db-bf70-ffc51067a339

**Comment by Valentine1898** [comment] 2024-07-08 17:36
I have already attempted to filter out zero-valued notes before saving them in the IDB. The issue is that we require zero-valued notes to display some transaction actions
https://github.com/penumbra-zone/web/pull/1138#issue-2308672184

**Comment by TalDerei** [comment] 2024-07-08 17:54
> I have already attempted to filter out zero-valued notes before saving them in the IDB. The issue is that we require zero-valued notes to display some transaction actions

https://github.com/penumbra-zone/web/blob/main/packages/wasm/crate/src/planner.rs#L500 defaults to the 3rd option: `"Save zero notes, but filter them only on retrieval where necessary"`. Can we close out this issue?

**Comment by Valentine1898** [comment] 2024-07-16 10:41
I think we can close this issue for now

**Closed by Valentine1898** 2024-07-16 10:41 UTC
Labels: refactor, enhancement
