### ISSUE TITLE
Pcli swap claim not detected by minifront

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1003] opened 2024-04-29 09:41 UTC
Steps to reproduce:

1. Ensure your pcli account is the same as the one for prax
2. Make a swap in plci. Something like
```
cargo run --release --bin pcli tx swap 33test_usd --into penumbra
```
3. Go to `/dashboard/transactions` in minifront and notice that swap claim is not present in list
4. Clear cache in Prax
5. After resyncing, note that swap claim is present

**Comment by Valentine1898** [comment] 2024-04-29 20:56
hard to reproduce

**Comment by jessepinho** [comment] 2024-06-14 20:42
Why is this blocked?

**Comment by Valentine1898** [comment] 2024-06-14 21:45
> Why is this blocked?

because it's actually a `pd` issue that should be solved in the penumbra repo https://github.com/penumbra-zone/penumbra/issues/4465 

But most likely we won't need any additional changes to the web repo, so we can just close this issue?

**Comment by jessepinho** [comment] 2024-06-14 23:06
OK cool. @grod220 can we close this? (since it's your ticket)

**Closed** 2024-06-17 08:28 UTC
Labels: bug, mainnet
