### ISSUE TITLE
provide address without connection permission

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1007] opened 2024-04-29 17:39 UTC
penumbra extension api might provide a way to acquire an address to the user's wallet without permitting full transaction log access. this could be implemented by

1. a new service that only provides addresses, plus per-service permissions in the extension
2. an address injected by content-script
3. a dedicated method to request an address injected by content-script

i favor 2 as the simplest technique, using an unconditionally injected random ephemeral address. is there any risk to making a random ephemeral address available to every page? could it be perhaps used for some kind of analysis, either alone or after collecting a large number of them?

**Comment by hdevalence** [comment] 2024-04-29 18:33
The problem with only giving access to one-time addresses is that it's undesirable from a product perspective. Because FMD is scoped to addresses, it's not possible to detect funds sent to one-time addresses via FMD. This means that encouraging the use of one-time addresses everywhere cuts out a tool we have to address performance as the network scales. Also, since one-time addresses are opaque, pervasive use of one-time addresses without thinking through the auditability / inspectability issue means that we could be training users to send funds to random addresses, allowing malicious sites to replace the addresses with attacker-controlled ones.

Previously, it was an explicit design decision not to have a finer-grained permissioning level than view (automatic) / custody (explicit user approval). If we want to change this, the way we should proceed is by designing a new capability model (in the abstract), with tiers of capability and deciding what should be in which tier and how a user is supposed to understand the different tiers of capability. 

The mechanics of how we'd implement those levels of capability are downstream of that, and I suspect (1) is the best approach, but the real complexity is at the product level of capability modeling, all of the proposed implementation options are of similar complexity (i.e., rounding to 0) relative to the problem of defining the capability levels.

I'd like to close this issue as "not planned" in favor of starting with the capability modeling (in a new issue), and then revisiting/reopening/duplicating it afterwards.

**Closed by hdevalence** 2024-04-29 18:33 UTC
