### ISSUE TITLE
Expected shares discrepency bug 🐞 

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1239] opened 2024-06-03 10:15 UTC
```
Error: [unknown] Tendermint error 1: failed to deliver transaction: executing transaction: 
given 1000000 unbonded stake, expected 795181 delegation tokens but description produces 795423
```

https://github.com/penumbra-zone/web/assets/16624263/8ed30a6d-3e5a-484c-84f9-8b356935d72e

**Comment by grod220** [comment] 2024-06-03 10:40
Hmm. Seems to be working now 🤔

**Comment by grod220** [comment] 2024-06-03 12:04
Helpful context @Valentine1898, thanks 🙏

**Comment by Valentine1898** [comment] 2024-06-03 12:07
when creating the transaction on the video, the block height was **366744**
And the epoch transition was in block **366857**
So I'm probably wrong. 

![Image](https://github.com/penumbra-zone/web/assets/25391690/75e1a09e-8e90-40ca-935d-38188f776215)

![Image](https://github.com/penumbra-zone/web/assets/25391690/78eab19d-7a9e-45e1-9e57-cea6e55ac977)

**Comment by Valentine1898** [comment] 2024-06-03 12:09
I'll try to reproduce this bug

**Comment by Valentine1898** [comment] 2024-06-03 12:35
Ah, okay, we'll close

**Comment by grod220** [comment] 2024-06-03 16:45
Should investigate a bit further to see if there are rounding errors on the client side

**Comment by Valentine1898** [comment] 2024-06-03 16:52
> Should investigate a bit further to see if there are rounding errors on the client side.

it doesn't look like a rounding error, because the expected value and the passed value have the same precision

<img width="600" alt="image" src="https://github.com/penumbra-zone/web/assets/25391690/9255e763-be8f-452d-ab69-72011fffd91c">

**Comment by TalDerei** [comment] 2024-06-03 19:33
will try reproducing this bug

**Comment by TalDerei** [comment] 2024-06-06 05:06
I could _not_ reproduce this bug after many varied delegation attempts.

**Comment by TalDerei** [comment] 2024-06-06 05:22
I think we can actually close this unless this bug surfaces more frequently? Importantly, we have stateful checks set in place to cause the delegation to fail in the presence of these sorts of irregularities.

**Comment by grod220** [comment] 2024-06-06 07:42
SGTM

**Comment by Valentine1898** [comment] 2024-06-10 10:20
This bug randomly reproduced for me
I don't think it's related to the epoch transition, because I was able to reproduce it several times within a few minutes

I'm assuming it's due to the fact that the validator data we have in indexed-db is not up to date for some reason 

Added context with screenshots, also seems @erwanor wanted to take a look at it 

![telegram-cloud-photo-size-2-5418385455231130302-y](https://github.com/penumbra-zone/web/assets/25391690/c504cab5-3cf0-4843-a781-74d81be1cab5)
![telegram-cloud-photo-size-2-5418385455231130309-y](https://github.com/penumbra-zone/web/assets/25391690/ff5bd545-7ba4-4c82-a845-000829afd00d)
![telegram-cloud-photo-size-2-5418385455231130312-y](https://github.com/penumbra-zone/web/assets/25391690/2dd7602f-9216-4972-8496-c961651376dc)

**Comment by erwanor** [comment] 2024-06-10 15:00
Great, do you have the block height as well? Unless you have a good idea on the approximate cause (e.g., IDB having stale data), @TalDerei this should be able to reproduce by:
1. Loading a fresh extension
2. Sync against a full node that stalls at the reported block height
3. Track the source of discrepancy / cross-reference the extension view's of the rate data with the one reported above

**Comment by Valentine1898** [comment] 2024-06-10 17:26
> Great, do you have the block height as well?
I didn't keep the exact height, but I can be sure that it was far from the epoch transition. 

I think the problem is that we are taking `validatorExchangeRate` to create delegate transaction plan from `validatorInfo` instead of using `CurrentValidatorRate rpc `

There is a potential problem with `validatorInfo`, which is that we update the validator data in indexed-db when transitioning epochs, but we do it in the last block of the epoch that ends, not in the first block of the new epoch. 
see: 
https://github.com/penumbra-zone/web/blob/fe0d7ae1cdaa7a35bc833971d862c3ec4875ca0e/packages/query/src/block-processor.ts#L353-L356

**Comment by Valentine1898** [comment] 2024-06-10 17:30
I can confirm that `validatorExchangeRate` obtained from `validatorInfo` and `validatorExchangeRate` obtained by `CurrentValidatorRate rpc` have different values for the same validator

@erwanor 

<img width="900" alt="image" src="https://github.com/penumbra-zone/web/assets/25391690/00dc5766-f07d-4d81-8ff7-abb79f544881">

**Comment by Valentine1898** [comment] 2024-06-10 17:37
I also noticed that pcli uses `CurrentValidatorRate rpc` instead of using `validatorExchangeRate` from `validatorInfo`
https://github.com/penumbra-zone/penumbra/blob/da3ef0a312c193d74c55bfd0282dad2affdb93d0/crates/bin/pcli/src/command/tx.rs#L503-L508

**Comment by Valentine1898** [comment] 2024-06-11 14:53
Turned out to be a core repo issue, see https://discord.com/channels/824484045370818580/1044457038886998137/1250096780880908298

**Closed by Valentine1898** 2024-06-11 14:53 UTC
Labels: bug
