### ISSUE TITLE
Port `ValueView` rendering logic and `Amount` parsing from Rust code

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#178] opened 2023-10-31 06:09 UTC
I sent a large amount of funds to myself and noticed precision issues:

<img width="476" alt="Screen Shot 2023-10-30 at 11 06 41 PM" src="https://github.com/penumbra-zone/web/assets/44879/fced1221-361a-4dd7-ae31-2af8b1fc8558">

The Rust code has fairly carefully written code for converting between 128-bit `Amount`s and a decimal string, and could be useful to port here. Or, alternatively, we could use that code directly, but that would mean putting wasm on the webapp, and that requires removing the giant proving parameters from the wasm crate.

**Comment by grod220** [comment] 2023-10-31 06:27
I ran into this while addressing this bug: https://github.com/penumbra-zone/web/issues/131. I'm currently working on fixing this now. The issue is transferring to/from the baseunit with exponents applied uses javascript `number` (which lacks the necessary precision). 

For this case, I think we can use `bignumber.js` and be ok. Another option is to add a second wasm crate with all the utilities not related to proving.

**Comment by grod220** [comment] 2023-10-31 11:57
Addressed in: https://github.com/penumbra-zone/web/pull/179. Frontend now uses BigNumber.js to handle arbitrary-precision arithmetic associated with converting to/from exponent version of asset amount.

**Closed by grod220** 2023-10-31 11:57 UTC
